PUT http://localhost:4000/Compras/updateCompras
content-type: application/json

{
    "fecha_compra" : "01-junio-2024", 
    "estado" : "Activo",
    "ubicacion": "carrera 65 #04 manizales, barrio Bengala"
}